config/routes.rb
PagedMedia::Application.routes.draw do
  get 'sibling_popup/show'

  resources :pages
  resources :collections
  resources :sections
  resources :pageds do
    resources :sections, shallow: true
    patch :reorder, on: :member
    get :page, on: :member
    get :pages, on: :member
    get :bookreader, on: :member
    get :validate, on: :member
    get :view, on: :member, controller: "catalog", action: "view"
  end

  root :to => "catalog#index"
  Blacklight.add_routes(self)
  HydraHead.add_routes(self)
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  get '/credits' => 'static_pages#credits'

  

end

app/models/collection.rb
class Collection < ActiveFedora::Base
  VALID_PARENT_CLASSES = [Collection]
  VALID_CHILD_CLASSES = [Collection, Paged]
  include Node

  has_metadata 'descMetadata', type: CollectionMetadata

  has_attributes :name, datastream: 'descMetadata', multiple: false

  validates :name, presence: true

  # Additional values to include in hash used by descendent/ancestry list methods
  def additional_hash_values
    {name: name}
  end

end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: [:show, :edit, :update, :destroy]

  def index
    @collections = Collection.all
  end

  def show
  end

  def new
    @collection = Collection.new
  end

  def edit
  end

  def create
    @collection = Collection.new(collection_params)

    respond_to do |format|
      if @collection.save
        format.html { redirect_to @collection, notice: 'Collection was successfully created.' }
        format.json { render action: 'show', status: :created, location: @collection }
      else
        format.html { render action: 'new' }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to @collection, notice: 'Collection was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @collection.destroy
    respond_to do |format|
      format.html { redirect_to collections_url }
      format.json { head :no_content }
    end
  end

  private
    def set_collection
      @collection = Collection.find(params[:id])
    end

    def collection_params
      params.require(:collection).permit(:name, :prev_sib, :next_sib, :parent, :children)
    end
end

app/views/collections/_form.html.erb
<%= form_for(@collection) do |f| %>
  <% if @collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
      <% @collection.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <ol>
    <li class='field'>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </li>
  </ol>

  <%= render 'nodes/node_form_fields', f: f %>

  <div class="actions collection_submit">
    <% if !@collection.new? %>
      <%= f.submit "Update" %>
    <% else %>
      <%= f.submit "Create" %>
    <% end %>
  </div>
<% end %>

app/views/collections/edit.html.erb
<div id="sidebar" class="span3">
  <%#= render partial: 'shared/side_navbar' %>
</div>

<div id="content" class="span9">
  <%= render_breadcrumbs %>
  <h1>Collection: Edit</h1>
  
  <%= render 'form' %>
  
  <%= link_to 'Show', @collection %> |
  <%= link_to 'Back', collections_path %>
</div>

app/views/collections/index.html.erb
<div id="sidebar" class="span3">
  <%#= render partial: 'shared/side_navbar' %>
</div>

<div id="content" class="span9">
  <%= render_breadcrumbs %>
  <h1>Listing Collections</h1>

  <table id='listCollections'>
    <thead>
      <tr>
        <th>Name</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @collections.each do |collection| %>
        <tr>
          <td><%= collection.name %></td>
          <td><%= link_to 'Show', collection %></td>
          <td><%= link_to 'Edit', edit_collection_path(collection) %></td>
          <td><%= link_to 'Destroy', collection, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= button_to 'New Collection', new_collection_path, :class=> "button", :method=> :get %>

</div>

app/views/collections/new.html.erb
<div id="sidebar" class="span3">
  <%#= render partial: 'shared/side_navbar' %> 
</div>

<div id="content" class="span9">
  <%= render_breadcrumbs %>
  <h1>Collection: New</h1>
  
  <%= render 'form' %>
  
  <%= link_to 'Back', collections_path %>

</div>

app/views/collections/show.html.erb
<div id="sidebar" class="span3">
  <%#= render partial: 'shared/side_navbar' %>
</div>

<div id="content" class="span9">
  <%= render_breadcrumbs %>
  <p id="notice"><%= notice %></p>

  <h2><%= @collection.name %></h2>

  <div class="pmp_collection_info">
    <ul>
      <li>Name: <%= @collection.name %></li>
    </ul>
    <%= render 'nodes/node_display_fields', node: @collection %>
    <div>
      <%= button_to 'Update', edit_collection_path(@collection), :method => :get %>
    </div>
  </div>
</div>