config/routes.rb
PagedMedia::Application.routes.draw do
  get 'sibling_popup/show'

  resources :pages
  resources :collections
  resources :sections
  resources :pageds do
    resources :sections, shallow: true
    patch :reorder, on: :member
    get :page, on: :member
    get :pages, on: :member
    get :bookreader, on: :member
    get :validate, on: :member
    get :view, on: :member, controller: "catalog", action: "view"
  end

  root :to => "catalog#index"
  Blacklight.add_routes(self)
  HydraHead.add_routes(self)
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  get '/credits' => 'static_pages#credits'

  

end

app/models/section.rb
class Section < ActiveFedora::Base
  VALID_PARENT_CLASSES = [Paged, Section]
  VALID_CHILD_CLASSES = [Section, Page]
  include Node

  has_metadata 'descMetadata', type: SectionMetadata

  has_attributes :name, datastream: 'descMetadata', multiple: false

  validates :name, presence: true

  # Additional values to include in hash used by descendent/ancestry list methods
  def additional_hash_values
    {name: name}
  end

end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: [:show, :edit, :update, :destroy]
  before_action :set_paged, only: [:index, :new, :create]

  def index
    if @paged
      @sections = Section.where(parent: @paged.pid)
    else
      @sections = Section.all
    end
  end

  def show
  end

  def new
    if @paged
      @section = Section.new(parent: @paged.pid)
    else
      @section = Section.new
    end
  end

  def edit
  end

  def create

    @paged = Paged.find(params[:section][:paged_id]) if params[:section][:paged_id]
    params[:section].delete :paged_id if params[:section][:paged_id]
    
    @section = Section.new(section_params)

    respond_to do |format|
      if @section.save
        if @paged
          format.html { redirect_to @paged, notice: 'Section was successfully created.'}
        else
          format.html { redirect_to @section, notice: 'Section was successfully created.' }
          format.json { render action: 'show', status: :created, location: @section }
        end
      else
        format.html { render action: 'new' }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to @section, notice: 'Section was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @section.destroy
    respond_to do |format|
      format.html { redirect_to paged_sections_path(@section.parent) }
      format.json { head :no_content }
    end
  end

  private
    def set_section
      @section = Section.find(params[:id])
    end

    def set_paged
      @paged = Paged.find(params[:paged_id]) if params[:paged_id]
    end

    def section_params
      
      params.require(:section).permit(:name, :prev_sib, :next_sib, :parent, :children, :paged_id )
    end
end

app/views/sections/_add_section_form.html.erb
<h3><a name="add-section" />Add Section</a></h3>
<%= form_for :section, url: { action: "create", controller: "sections" }, html: {id: "add_section"} do |f| %>
  <%= f.hidden_field(:parent, value: @paged.id) %>
  <%= f.hidden_field(:paged_id, value: @paged.id) %>
  <div class="span4 add_section">
    <ol>
      <li class='field'>
        <%= f.label :name %>
        <%= f.text_field :name %>
      </li>
    </ol>
  </div>
  <div class="span4 add_section">
    <ol>
      <li>
        <%= f.label 'Previous node:' %>
        <%= f.text_field :prev_sib %>
      </li>
      <li>
        <%= f.label 'Next node:' %>
        <%= f.text_field :next_sib %>
      </li>
    </ol>
  </div>
  <div class="add-section-save">
    <%= f.submit "Save", :class => 'save_submit' %>
  </div>
<% end %>

app/views/sections/_form.html.erb
<%= form_for([@paged, @section]) do |f| %>
  <% if @section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
      <% @section.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <ol>
    <li class='field'>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </li>
  </ol>

  <%= render 'nodes/node_form_fields', f: f %>

  <div class="actions section_submit">
    <% if !@section.new? %>
      <%= f.submit "Update" %>
    <% else %>
      <%= f.submit "Create" %>
    <% end %>
  </div>
<% end %>

app/views/sections/edit.html.erb
<div id="sidebar" class="span3">
  <%#= render partial: 'shared/side_navbar' %>
</div>

<div id="content" class="span9">
  <%= render_breadcrumbs %>
  <h1>Section: Edit</h1>
  
  <%= render 'form' %>
  
  <%= link_to 'Show', @section %> |
  <% unless @section.parent.blank? || @section.parent != @section.ancestor_of_class(Paged) %>
    <%= link_to 'Back', paged_sections_path(@section.parent) %>
  <% else %>
    <%= link_to 'Back', sections_path %>
  <% end %>
</div>

app/views/sections/index.html.erb
<div id="sidebar" class="span3">
  <%#= render partial: 'shared/side_navbar' %>
</div>

<div id="content" class="span9">
  <%= render_breadcrumbs %>
  <h1>Listing Sections</h1>

  <table id='listSections'>
    <thead>
      <tr>
        <th>Name</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @sections.each do |section| %>
        <tr>
          <td><%= section.name %></td>
          <td><%= link_to 'Show', section %></td>
          <td><%= link_to 'Edit', edit_section_path(section) %></td>
          <td><%= link_to 'Destroy', section, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <% if @paged %>
    <%= button_to 'New Section', new_paged_section_path(@paged), :class=> "button", :method=> :get %>
  <% else %>
    <%= button_to 'New Section', new_section_path, :class=> "button", :method=> :get %>
  <% end %>

</div>

app/views/sections/new.html.erb
<div id="sidebar" class="span3">
  <%#= render partial: 'shared/side_navbar' %> 
</div>

<div id="content" class="span9">
  <%= render_breadcrumbs %>
  <h1>Section: New</h1>
  
  <%= render 'form' %>

  <% if @paged %>  
    <%= link_to 'Back', paged_sections_path(@paged) %>
  <% else %>
    <%= link_to 'Back', sections_path %>
  <% end %>

</div>

app/views/sections/show.html.erb
<div id="sidebar" class="span3">
  <%#= render partial: 'shared/side_navbar' %>
</div>

<div id="content" class="span9">
  <%= render_breadcrumbs %>
  <p id="notice"><%= notice %></p>

  <h2><%= @section.name %></h2>

  <div class="pmp_section_info">
    <ul>
      <li>Name: <%= @section.name %></li>
    </ul>
    <%= render 'nodes/node_display_fields', node: @section %>
    <div>
      <%= button_to 'Update', edit_section_path(@section), :method => :get %>
    </div>
  </div>
</div>