config/routes.rb
PagedMedia::Application.routes.draw do
  get 'sibling_popup/show'

  resources :pages
  resources :collections
  resources :sections
  resources :pageds do
    resources :sections, shallow: true
    patch :reorder, on: :member
    get :page, on: :member
    get :pages, on: :member
    get :bookreader, on: :member
    get :validate, on: :member
    get :view, on: :member, controller: "catalog", action: "view"
  end

  root :to => "catalog#index"
  Blacklight.add_routes(self)
  HydraHead.add_routes(self)
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  get '/credits' => 'static_pages#credits'

  

end

app/models/paged.rb
# A binding of Page objects.
#--
# Copyright 2014 Indiana University.

class Paged < ActiveFedora::Base

  validates :issued,
  format: { with: /\A(19|20)\d\d([- \/.])(0[1-9]|1[012])\2(0[1-9]|[12][0-9]|3[01])\z/,
    message: "Date format must be yyyy-mm-dd",
    allow_blank: true }
  
  VALID_PARENT_CLASSES = [Collection]
  VALID_CHILD_CLASSES = [Section, Page]
  include Node

  has_file_datastream 'pagedXML'

  has_metadata "descMetadata", type: PagedDescMetadata, label: 'PMP PagedObject descriptive metadata'

  # Single-value fields
  has_attributes :title, :contributor, :creator, :coverage, :issued, :date, :description,
                 :identifier, :language, :publisher, :publisher_place,
                 :rights, :source, :subject, :type, datastream: :descMetadata, multiple: false
  # Multi-value fields
  has_attributes :paged_struct, datastream: :descMetadata, multiple: true

  before_save :update_paged_struct

  # Setter for the XML datastream
  def xml_file=(file)
    ds = @datastreams['pagedXML']
    ds.content = file
    ds.mimeType = 'application/xml'
    ds.dsLabel = file.original_filename
  end

  # Getter for the XML datastream
  def xml_file
    @datastreams['pagedXML']
  end

  def xml_datastream
    @datastreams['pagedXML']
  end

  # Additional values to include in hash used by descendent/ancestry list methods
  def additional_hash_values
    {title: title}
  end

  def to_solr(solr_doc={}, opts={})
    pages = self.list_descendents(Page)
    super(solr_doc, opts)
    solr_doc[Solrizer.solr_name('pages', 'ss')] = pages.to_json # single value field as json
    solr_doc[Solrizer.solr_name('pages', 'ssm')] = pages # multivalue field as ruby hash
    solr_doc[Solrizer.solr_name('item_id', 'si')] = self.pid
    return solr_doc
  end

  def update_paged_struct(delimiter = '--')
    new_struct = []
    self.list_ancestors(Collection).reverse_each do |collection|
      new_struct.unshift(collection[:name])
    end
    new_struct.each_with_index do |value, index|
      new_struct[index] = new_struct[index - 1] + delimiter + value unless index == 0
    end
    self.paged_struct = new_struct
  end

end

app/controllers/pageds_controller.rb
class PagedsController < ApplicationController
  before_action :set_paged, only: [:show, :edit, :update, :destroy, :bookreader, :validate, :reorder]

  # GET /pageds
  # GET /pageds.json
  def index
    @pageds = Paged.all
    @image_urls = {}
    @pageds.each do |paged|
      pages = find_pages(paged.pid)
      ordered = JSON.parse(pages) rescue false
      if ordered && ordered.count > 0 
        @image_urls[paged.pid] = ordered[0]['ds_url']
      end
    end

    add_breadcrumb "Browse", pageds_path
  end

  # GET /pageds/1
  # GET /pageds/1.json
  def show
    @ordered = JSON.parse(find_pages())
    add_breadcrumb @paged.title, @paged
  end

  def validate
    @ordered = JSON.parse(find_pages())
    validated, @error = @paged.order_children()
    if @error
      flash.now[:error] = "ERROR Ordering Items : #{@error}"
    end
    respond_to do |format|
      format.html { render action: 'show' }
      format.json { render action: 'show' }
    end
  end

  # GET /pageds/new
  def new
    @paged = Paged.new
    add_breadcrumb "Add Paged Media", new_paged_path
  end

  # GET /pageds/1/edit
  def edit
    @ordered = JSON.parse(find_pages())
    add_breadcrumb @paged.title, @paged
    add_breadcrumb "Edit"
  end

  # POST /pageds
  # POST /pageds.json
  def create
    @paged = Paged.new(paged_params)

    respond_to do |format|
      if @paged.save
        format.html { redirect_to @paged, notice: 'Paged was successfully created.' }
        format.json { render action: 'show', status: :created, location: @paged }
      else
        format.html { render action: 'new' }
        format.json { render json: @paged.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pageds/1
  # PATCH/PUT /pageds/1.json
  def update
    respond_to do |format|
      if @paged.update(paged_params)
        format.html { redirect_to @paged, notice: 'Paged was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @paged.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pageds/1
  # DELETE /pageds/1.json
  def destroy
    @paged.destroy
    respond_to do |format|
      format.html { redirect_to pageds_url }
      format.json { head :no_content }
    end
  end

  # GET /pageds/1/pages
  # GET /pageds/1/pages.json
  def pages
    page_rsp = {}
    search = find_pages
    parsed = JSON.parse(search)
    if params[:index].nil?
      page_rsp = parsed
    else
      unless params[:index].to_i > parsed.count
        page_id = parsed[params[:index].to_i]['id']
        ds_url = parsed[params[:index].to_i]['ds_url']
        logical_number = parsed[params[:index].to_i]['logical_number']
        ds_url ||= ''
        page_rsp = {:id => page_id, :index => params[:index], :logical_number => logical_number, :ds_url => ds_url}
      else
        page_rsp = {:id => params[:id], :index => params[:index], :error => 'Index out of bounds'}
      end
    end
    respond_to do |format|
      format.html { render json: page_rsp, head: :no_content }
      format.json { render json: page_rsp, head: :no_content}
    end
  end

  def bookreader
    render layout: false
  end

  # PATCH /pageds/1/reorder
  def reorder
    unless params[:reorder_submission].nil? || params[:reorder_submission].blank?
      parsed_ids = JSON.parse(params[:reorder_submission])
      @paged.restructure_children(parsed_ids)
      flash[:notice] = 'Reordered pages.'
    else
      flash[:notice] = "No changes to the page order were submitted."
    end
    redirect_to action: :edit
  end

  private

  def find_pages(*args) 
    if args.size > 0
      params[:id] = args[0]
    end
    pages = {}
    search = ActiveFedora::SolrService.instance.conn.select :params => { :q => params[:id], :fl => "pages_ss" }
    unless search['response']['numFound'].to_i == 0
      pages = search['response']['docs'][0]['pages_ss']
    else
      pages = {:id => params[:id], :error => 'No pages'}
    end
    #FIXME: keep?
    pages ||= "[]"
    return pages
  end

    # Use callbacks to share common setup or constraints between actions.
    def set_paged
      @paged = Paged.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def paged_params
      params.require(:paged).permit(:type, :title, :creator, :publisher, :publisher_place, :issued, :xml_file, :prev_sib, :next_sib, :parent, :children)
    end

    def reorder_params
      params.permit(:reorder_submission)
    end
end

app/helpers/pageds_helper.rb
module PagedsHelper

  def i18n_set? key
    I18n.t key, :raise => true rescue false
  end

end

app/views/pageds/_form.html.erb
<%= form_for(@paged) do |f| %>
  <% if @paged.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@paged.errors.count, "error") %> prohibited this paged from being saved:</h2>

      <ul>
      <% @paged.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  
  <ol>
    <li>
      <%= f.label :type %>
      <%= f.select(:type) do %>
        <% if !@paged.type %>
          <option value='' disabled selected>Select type</option>
        <% end %>
        <% if i18n_set? 'pagedmedia' %>
          <% I18n.t('pagedmedia').each do |ctype, cinfo| %>
            <% if @paged.type && @paged.type.to_s == ctype.to_s %>
              <%= content_tag(:option, cinfo[:label] , value: ctype, selected: 'selected') %>
            <% else %>
              <%= content_tag(:option, cinfo[:label] , value: ctype) %>
            <% end %>
          <%end %>
        <% end %>
      <% end %>
    </li>
    <li>
      <%= f.label :title %>
      <%= f.text_field :title %>
      
    </li>
    <li class="field">
      <%= f.label :creator %>
      <%= f.text_field :creator %>
    </li>
    <li class="field">
      <%= f.label :publisher %>
      <%= f.text_field :publisher %>
    </li>
      <li class="field">
      <%= f.label :publisher_place %>
      <%= f.text_field :publisher_place %>
    </li>
    <li class="field">
      <%= f.label "Date of Publication" %>
      <%= f.text_field :issued, placeholder: 'yyyy-mm-dd' %>
    </li>
    <li class='field'>
      <%= f.label 'XML File' %>
      <div class="custom-upload">
        <%= f.file_field :xml_file %>
        <div class="fake-file">
          <input disabled="disabled" placeholder="<%= @paged.xml_datastream.label %>">
        </div>
      </div>
    </li>
    <li class="field">
      <label/>
      <div class="actions paged_submit">
      <% if !@paged.new? %>
        <%= f.submit "Save", :class => 'save_submit' %>
      <% else %>
        <%= f.submit "Create"%>
      <% end %>
      </div>
    </li>

  </ol>
  
  <div style="clear:both;"></div>

  <%#= render 'nodes/node_form_fields', f: f %>

<% end %>

app/views/pageds/_paged_pages.html.erb
<div id="paged_pages" style="padding-bottom:25px;">
  <h3>Manage Pages</h3>
  <!-- <p><strong>Number of pages : </strong><%= paged.children.size %></p> -->
  <% session[:came_from] = :paged %>
  <div  id="pages">
    <table id="paged-pages-table">
      <tr>
        <th></th>
        <th class="paged-pages-table-triple">Page Number</th>
        <th class="paged-pages-table-triple">Identifier</th>
        <th>View Page</th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>
      <% ordered.each do |page| %>
        <% my_page = Page.find(page['id']) %>
        <tr class="<%= cycle('odd', 'even') %>">
          <td></td>
          <td class='logical_numbers'><%= page['logical_number'] %></td>
          <td><%= my_page.pid %></td>
          <td>
            <%= link_to page_path(page["id"]) do %>
              <i class="fa fa-file-text-o fa-2x"></i>
            <% end %>
          </td>
          <td>
            <%= link_to edit_page_path(page["id"]) do %>
              <i class="fa fa-pencil fa-2x"></i>
            <% end %>
          </td>
          <td>
            <%= link_to page_path(page["id"]), method: :delete, data: { confirm: 'Are you sure?' } do %>
              <span class="fa-stack ">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-times fa-stack-1x fa-inverse"></i>
              </span>
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/pageds/_reorder_pages.html.erb
<div id="reorder_pages_container">
  <p><strong>Structure</strong><p>
  <p>Drag pages to reorder them.</p>
  <div style="clear:right"></div>

  <div id="reorder_pages">
    <%= form_for(@paged, url: { action: :reorder }) do |f| %>
      <ol id="sortable_pages" class="sortable_pages ol_drag">
        <% @paged.order_child_objects[0].each do |child| %>
          <%= render partial: 'reorder_section', locals: { child: child } %>
        <% end %>
      </ol>
      <input id="reorder_submission" name="reorder_submission" type="hidden" value="">
      <%= f.submit "Reorder", :class => 'reorder_button sortable_save' %> 
    <% end %>
  </div>
</div>

app/views/pageds/_reorder_section.html.erb
<li id="<%= child.pid %>" class="li_drag" data-id="<%= child.pid %>">

  <!-- <i class="fa fa-bars fa-2x"></i> -->
  <!--
  <%= child.class.to_s %>: <%= child.class == Page ? child.logical_number : child.name %> (<%= child.pid %>)
  -->
  <% if child.class == Section %>
    <%= child.class == Page ? child.logical_number : child.name %>
    <ol class="ol_drag">
      <%# FIXME: handle empty section %>
      <% child.order_child_objects[0].each do |grandchild| %>
        <%= render partial: 'reorder_section', locals: { child: grandchild } %>
      <% end %>
    </ol>
  <% else %>
    <%= child.class == Page ? child.logical_number : child.name %>
  <% end %>
  
</li>

app/views/pageds/bookreader.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
    <title>bookreader demo</title>

    <%= stylesheet_link_tag "BookReader" %>
    <!-- Custom CSS overrides -->
    <%= stylesheet_link_tag "BookReaderDemo" %>
    <script type="text/javascript">
       var paged_id = '<%= @paged.pid %>';
    </script>

    <script type="text/javascript" src="http://www.archive.org/includes/jquery-1.4.2.min.js"></script>
    <script type="text/javascript" src="http://www.archive.org/bookreader/jquery-ui-1.8.5.custom.min.js"></script>

    <script type="text/javascript" src="http://www.archive.org/bookreader/dragscrollable.js"></script>
    <script type="text/javascript" src="http://www.archive.org/bookreader/jquery.colorbox-min.js"></script>
    <script type="text/javascript" src="http://www.archive.org/bookreader/jquery.ui.ipad.js"></script>
    <script type="text/javascript" src="http://www.archive.org/bookreader/jquery.bt.min.js"></script>

    <%= javascript_include_tag "BookReader.js" %>
</head>
<body style="background-color: #939598;">

<div id="BookReader">
    Internet Archive BookReader Demo    <br/>
    
    <noscript>
    <p>
        The BookReader requires JavaScript to be enabled. Please check that your browser supports JavaScript and that it is enabled in the browser settings.  You can also try one of the <a href="http://www.archive.org/details/goodytwoshoes00newyiala"> other formats of the book</a>.
    </p>
    </noscript>
</div>
<div id="foo">
  <%= @paged %>
</div>

<%= javascript_include_tag "BookReaderJSSimple.js" %>

</body>
</html>

app/views/pageds/edit.html.erb
<div id="sidebar" class="span3">
  <%#= render partial: 'shared/side_navbar' %>
  
   <div id="holding_pen">
    <h3>Holding Pen</h3>
    <ol class="holding_pages ol_drag">
      
    </ol>
    <!--
    <a id="moveItemsStart">Move Items to Start</a> <br/>
    <a id="moveItemsEnd">Move Items to End</a>
    -->
    <%= button_tag('Move to Front', id: 'move_to_front', class: 'move_button') %> <br/>
    <%= button_tag('Move to Back', id: 'move_to_back', class: 'move_button') %>
  </div> 
  
</div>

<div id="content" class="span9">
  <%= render_breadcrumbs %>
  <h3>Description</h3>
  
  <%= render 'form' %>
  <%= render partial: 'reorder_pages', locals: { paged: @paged, ordered: @ordered } %>
  
  
  
</div>

app/views/pageds/index.html.erb
<div id="sidebar" class="span3">
  <%= render partial: 'shared/side_navbar' %>
</div>
 
<% i = 0 %>
 
<div id="content" class="span9">
  <%= render_breadcrumbs %>
  
  <table id='listPageds'>
    <tbody>
      <% @pageds.each do |paged| %>  
        <tr style="font-weight: bold;">
          <td><%= i += 1 %>.</td>
          <td><%= link_to paged.title, paged %></td>
          <td rowspan=6>
            <% if @image_urls[paged.pid] %>
              <%= image_tag(@image_urls[paged.pid], height: "100", width: "100" ) %>
            <% end %>
          </td>
        </tr>
        <tr>
          <td>Creator:</td>
          <td><%= paged.creator %></td>
        </tr>
        <tr>
          <td>Publisher:</td>
          <td><%= paged.publisher %></td>
        </tr>
        <tr>
          <td>Publisher Place:</td>
          <td><%= paged.publisher_place %></td>
        </tr>
        <tr>
          <td>Type:</td>
          <td><%= paged.type %></td>
        </tr>
        <tr>
          <td>Issued:</td>
          <td><%= paged.issued %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
 
  <br/><br/>

</div>

app/views/pageds/new.html.erb
<div id="sidebar" class="span3">
  <%#= render partial: 'shared/side_navbar' %>
</div>

<div id="content" class="span9">
  <%= render_breadcrumbs %>
  <h1>Paged Media: New</h1>
  
  <%= render 'form' %>
  
  <%= link_to 'Back', pageds_path %>

</div>

app/views/pageds/show.html.erb
<div id="sidebar" class="span3">
  <%#= render partial: 'shared/side_navbar' %>
</div>

<div id="content" class="span9">
  <%= render_breadcrumbs %>
  <p id="notice"><%= notice %></p>
  
  <h3><%= @paged.title %></h3>
    <div>
      <table id="paged-show-table">
        <tr>
          <td rowspan=2>
            <div class="pmp_paged_info">
              <ul>
                <% if i18n_set? 'pagedmedia.' + @paged.type + '.fields' %>
                  <% vocabs =  I18n.t 'pagedmedia.' + @paged.type + '.fields' %>
                <% else %>
                  <% vocabs =  I18n.t 'pagedmedia.default.fields' %>
                <% end %>
                <% vocabs.each do |vocab, fields| %>
                  <% fields.each do |key, value| %>
                    <% if (@paged.respond_to? key) && (@paged.send(key) != NIL) %>
                     <li><%= t(value)%>: <%= @paged.send(key) %></li>
                    <% end %>
                  <% end %>
                <% end %>    
              
                <li>XML file:
                  <% if @paged.xml_file.has_content? %>
                    <%= link_to @paged.xml_datastream.label,
                                ActiveFedora.fedora_config.credentials[:url] +
                                  '/' + @paged.xml_datastream.url %>
                  <% else %>
                    none.
                  <% end %>
                </li>
              </ul>
            </div>            
          </td>
          <th>Add Page</th>
          <th>Add Section</th>
          <th>View</th>
          <th>Edit</th>
          <th>Delete</th>
        </tr>
        <tr>
          <td>
            <%= link_to '<i class="fa fa-plus-circle fa-2x"></i>'.html_safe, paged_path(@paged, :add => 'page', :anchor => 'add-page')  %>
          </td>
          <td>
            <%= link_to '<i class="fa fa-plus-circle fa-2x"></i>'.html_safe, paged_path(@paged, :add => 'section', :anchor => 'add-section')  %>
          </td>
          <td>
            <%= link_to bookreader_paged_path(@paged) + '#page/1/mode/2up', target: "_blank"  do %>
              <i class="fa fa-file-text-o fa-2x"></i>
            <% end %>
          </td>
          <td>
            <%= link_to edit_paged_path(@paged) do %>
              <i class="fa fa-pencil fa-2x"></i>
            <% end %>          
          </td>
          <td>
            <%= link_to @paged, method: :delete, data: { confirm: 'Are you sure?' }  do %>
              <span class="fa-stack ">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-times fa-stack-1x fa-inverse"></i>
              </span>
            <% end %>         
          </td>
        </tr>
      </table>
    </div>

  <!-- Cover Image -->
  <!--
  <div style="float:left; padding-left:50px; text-align:center;">
    <% if @ordered[0] %>
      <%= image_tag(@ordered[0]["ds_url"], height: "100", width: "100" ) %>
    <% end %>
    <%# button_to 'View in BookReader', bookreader_paged_path(@paged) + '#page/1/mode/2up', target: "_blank", :method => :get %>
    <div>
      <%= link_to "<button>View in BookReader</button>".html_safe, bookreader_paged_path(@paged) + '#page/1/mode/2up', target: "_blank", class: "button_link" %>
    </div>
  </div>
  -->
  
  <div style="clear:both;"></div>
  
  <div id='pages'>
    <%= render :partial=>'paged_pages', :locals => { :paged => @paged, :ordered => @ordered } %>
  </div>
  
  <% if params.has_key?(:add) %>
    <% if params[:add] == 'page' %>
      <%= render :partial=>'pages/add_page_form' %>
    <% elsif params[:add] == 'section' %>
      <%= render :partial=>'sections/add_section_form' %>
    <% end %>
  <% end %>
  
  
</div>