config/routes.rb
PagedMedia::Application.routes.draw do
  get 'sibling_popup/show'

  resources :pages
  resources :collections
  resources :sections
  resources :pageds do
    resources :sections, shallow: true
    patch :reorder, on: :member
    get :page, on: :member
    get :pages, on: :member
    get :bookreader, on: :member
    get :validate, on: :member
    get :view, on: :member, controller: "catalog", action: "view"
  end

  root :to => "catalog#index"
  Blacklight.add_routes(self)
  HydraHead.add_routes(self)
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  get '/credits' => 'static_pages#credits'

  

end

app/views/pages/_add_page_form.html.erb
<h3><a name="add-page" />Add Page</a></h3>
<%= form_for :page, url: { action: "create", controller: "pages" }, html: {id: "add_page"} do |f| %>
  <%= f.hidden_field(:parent, value: @paged.id) %>
  <div class="span4 add_page">
    <ol>
    <li class="field">
      <%= f.label :logical_number %>
      <%= f.text_field :logical_number %>
    </li>
    <li class="field">
      <%= f.label 'Previous page' %>
      <%= f.text_field :prev_sib %>
    </li>
    <li class="field">
      <%= f.label 'Next page' %>
      <%= f.text_field :next_sib %>
    </li>
    </ol>
  </div>
  <div class="span4 add_page">
    <ol>
      <li class='field'>
        <%= f.label 'Page image file:' %>
        <div class="custom-upload custom-upload-small">
          <%= f.file_field :image_file %>
          <div class="fake-file">
            <input disabled="disabled">
          </div>
        </div>
      </li>
      <br/>
      <li class='field'>
        <%= f.label 'New OCR file:' %>
        <div class="custom-upload custom-upload-small">
          <%= f.file_field :ocr_file %>
          <div class="fake-file">
            <input disabled="disabled">
          </div>
        </div>        
      </li>
      <br/>
      <li class='field'>
        <%= f.label 'XML file:' %>
        <div class="custom-upload custom-upload-small">
          <%= f.file_field :xml_file %>
          <div class="fake-file">
            <input disabled="disabled">
          </div>
        </div>        
      </li>
    </ol>
  </div>
  <div class="add-page-save">
    <%= f.submit "Save", :class => 'save_submit' %>
  </div>
<% end %>

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <ol>
    <li>
      <%= f.label :logical_number %>
      <%= f.text_field :logical_number %>
    </li>
    
    <!-- Display all available Metadata fields according to local file -->
    <% if @paged && (i18n_set? 'pagemedia.' + @paged.type + '.fields') %>
      <% vocabs =  I18n.t 'pagemedia.' + @paged.type + '.fields' %>
    <% else %>
      <% vocabs =  I18n.t 'pagemedia.default.fields' %>
    <% end %>
    <% vocabs.each do |vocab, fields| %>
      <% fields.each do |key, value| %>
        <% if (@page.respond_to? key) %>
          <li>
            <%= f.label value %>
            <%= f.text_field key %>
          </li>
        <% end %>
      <% end %>
    <% end %>
    
    <li>
      <%= f.label 'Parent paged:' %>
      <%= f.text_field :parent %>
    </li>
    <li>
      <%= f.label 'Previous page:' %>
      <%= f.text_field :prev_sib %>
    </li>
    <li>
      <%= f.label 'Next page:' %>
      <%= f.text_field :next_sib %>
    </li>
    <!-- OCR File -->
    <% if !@page.new? %>
    <li>
      <span class="form_label">Current OCR File</span>
      <span class="form_field">
        <%= link_to @page.ocr_datastream.label, ActiveFedora.fedora_config.credentials[:url] + '/' + @page.ocr_datastream.url %>
      </span>
    </li>
    <% end %>
    <li>
      <%= f.label 'New OCR file:' %>
      <%= f.file_field :ocr_file %>
    </li>
    <li>&nbsp;</li> 
    <!-- XML File -->
    <% if !@page.new? %>
    <li>&nbsp;</li>  
    <li>
      <span class="form_label">Current XML file</span>
      <span class="form_field">
      <% if @page.xml_datastream.has_content? %>
        <%= link_to @page.xml_datastream.label, ActiveFedora.fedora_config.credentials[:url] + '/' + @page.xml_datastream.url %>
      <% else %>
        none.
      <% end %>
      </span>
    </li>
    <% end %>
    <li>
      <%= f.label 'New XML file:' %>
      <%= f.file_field :xml_file %>
    </li>
    <li>&nbsp;</li>
    <!-- Page image -->
    <li>
      <% if !@page.new? %>
      <span class="form_label">Current image</span>
      <span class="form_field">
      <img alt='<%=  @page.image_datastream.label %>'
           src='<%=  ActiveFedora.fedora_config.credentials[:url] %>/<%=  @page.image_datastream.url %>'
           width='128' height='128' />
      <!-- FIXME if our Fedora instance is inaccessible then we need another way to do this -->
      </span>
      <% end %>
      <%= f.label 'New page image file:' %>
      <%= f.file_field :image_file %>
    </li>
  </ol>
  
  <div class="actions page_submit">
    <% if !@page.new? %>
      <%= f.submit "Update"%>
    <% else %>
      <%= f.submit "Create"%>
    <% end %>
  </div>
  
<% end %>

app/views/pages/edit.html.erb
<div id="sidebar" class="span3">
  <%#= render partial: 'shared/side_navbar' %>
</div>

<div id="content" class="span9">
  <%= render_breadcrumbs %>
  <h1>Page: Edit </h1>
  
  <%= render 'form' %>

  <%= link_to 'Show', href: page_path(@page), title: 'Show' do %>
    <i class='fa fa-eye fa-2x'></i>
  <% end %> |
  <%= link_to 'Back', href: pages_path(), title: 'Back' do %>
    <i class='fa fa-hand-o-left fa-2x'></i>
  <% end %>
</div>

app/views/pages/index.html.erb
<div id="sidebar" class="span3">
  <%#= render partial: 'shared/side_navbar' %>
</div>

<div id="content" class="span9">
  <%= render_breadcrumbs %>
  <h1>Listing pages</h1>
  
  <table class='list_pages'>
    <thead>
      <tr>
        <th>Logical number</th>
        <th>Previous page</th>
        <th>Next page</th>
        <th>Show</th>
        <th>Edit</th>
        <th>Destroy</th>
      </tr>
    </thead>
  
    <tbody>
      <% @pages.each do |page| %>
        <tr>
          <td><%= page.logical_number %></td>
          <td><%= page.prev_sib %></td>
          <td><%= page.next_sib %>
          <td>
            <%= link_to 'Show', href: page_path(page) do %>
              <i class='fa fa-eye fa-2x'></i>
            <% end %>
          </td>
          <td>
            <%= link_to 'Edit',  href: edit_page_path(page) do %>
              <i class='fa fa-pencil fa-2x'></i>
            <% end %>
          </td>
          <td>
            <%= link_to 'Destroy', href: page_path(page), method: :delete, data: { confirm: 'Are you sure?' } do %>
              <span class='fa-stack'>
                <i class='fa fa-circle fa-stack-2x'></i>
                <i class='fa fa-times fa-stack-1x fa-inverse'></i>
              </span>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  <br>
  
  <%= button_to 'New Page', new_page_path %>

</div>

app/views/pages/new.html.erb
<div id="sidebar" class="span3">
  <%#= render partial: 'shared/side_navbar' %>
</div>

<div id="content" class="span9">
  <%= render_breadcrumbs %>
  <h1>New page</h1>
  
  <%= render 'form' %>
  
  <%= link_to 'Back', pages_path %>
</div>

app/views/pages/show.html.erb
<div id="sidebar" class="span3">
  <%#= render partial: 'shared/side_navbar' %>
</div>

<div id="content" class="span9">
  <%= render_breadcrumbs %>
  <i class='fa fa-cog fa-2x'
     onclick="show_sibling_popup('<%= @page.parent %>', '<%= @page.prev_sib %>', '<%= @page.next_sib %>', '<%= @page.id %>');"
     style='cursor: pointer; float: right;'></i>
  <p id="notice"><%= notice %></p>

  <h1>Page <%= @page.id %></h1>

  <!-- FIXME if our Fedora instance is inaccessible then we need another way to do this -->
  
  <div class="pmp_paged_info">
    <ul>
      <li>Logical Number: <%= @page.logical_number %></li>
      <% if @paged %>
      <li>
        Page from:
        <%= link_to @paged.title, paged_path(@paged) %>
      </li>
      <% end %>
      
      <% if @paged && (i18n_set? 'pagemedia.' + @paged.type + '.fields') %>
        <% vocabs =  I18n.t 'pagemedia.' + @paged.type + '.fields' %>
      <% else %>
        <% vocabs =  I18n.t 'pagemedia.default.fields' %>
      <% end %>
      <% vocabs.each do |vocab, fields| %>
        <% fields.each do |key, value| %>
          <% if (@page.respond_to? key) && (@page.send(key) != NIL) %>
           <li><%= t(value)%>: <%= @page.send(key) %></li>
          <% end %>
        <% end %>
      <% end %>
      
      <li>Parent Paged: <%= @page.parent %></li>
      <li>Previous Page: <%= @page.prev_sib %></li>
      <li>Next Page: <%= @page.next_sib %></li>
      <% if @page.ocr_file %>
      <li>  
        OCR File: <%= link_to @page.ocr_datastream.label, ActiveFedora.fedora_config.credentials[:url] + '/' + @page.ocr_datastream.url %> 
      </li>
      <% end %>
      <li>
        XML file:
       <% if @page.xml_file.has_content? %>
         <%= link_to @page.xml_datastream.label,
              ActiveFedora.fedora_config.credentials[:url] +
              '/' + @page.xml_datastream.url %>
        <% else %>
          none.
        <% end %>
    </ul>
  </div>
  
  <div style="float:left; padding-left:50px; text-align:center;">
    <a href="<%=  ActiveFedora.fedora_config.credentials[:url] %>/<%=  @page.image_datastream.url %>">
      <img alt='<%=  @page.image_datastream.label %>'
           src='<%=  ActiveFedora.fedora_config.credentials[:url] %>/<%=  @page.image_datastream.url %>'
           width='128' height='128'
           style='margin-right: 10px; float: left;'/>
    </a>
  </div>  
      
  <div style="clear:both"></div>    
  
  <%= link_to 'Edit', href: edit_page_path(@page), title: 'Edit' do %>
    <i class='fa fa-pencil fa-2x'></i>
  <% end %> |
  <%= link_to 'Back', href: pages_path(), title: 'Back' do %>
    <i class='fa fa-hand-o-left fa-2x'></i>
  <% end %>

</div>